=begin
#elepay API リファレンス

#elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。

The version of the OpenAPI document: 1.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

# Common files
require 'elepay-ruby-sdk/api_client'
require 'elepay-ruby-sdk/api_error'
require 'elepay-ruby-sdk/version'
require 'elepay-ruby-sdk/configuration'

# Models
require 'elepay-ruby-sdk/models/charge_capture_req'
require 'elepay-ruby-sdk/models/charge_date_time_type'
require 'elepay-ruby-sdk/models/charge_dto'
require 'elepay-ruby-sdk/models/charge_req'
require 'elepay-ruby-sdk/models/charge_status_type'
require 'elepay-ruby-sdk/models/charge_verify_req'
require 'elepay-ruby-sdk/models/charges_response'
require 'elepay-ruby-sdk/models/customer_dto'
require 'elepay-ruby-sdk/models/customer_req'
require 'elepay-ruby-sdk/models/customer_response'
require 'elepay-ruby-sdk/models/payment_method_type'
require 'elepay-ruby-sdk/models/provider_config_dto'
require 'elepay-ruby-sdk/models/refund_dto'
require 'elepay-ruby-sdk/models/refund_req'
require 'elepay-ruby-sdk/models/refund_status_type'
require 'elepay-ruby-sdk/models/refunds_dto'
require 'elepay-ruby-sdk/models/refunds_response'
require 'elepay-ruby-sdk/models/resource_type'
require 'elepay-ruby-sdk/models/sort_order_type'
require 'elepay-ruby-sdk/models/source_confirm_req'
require 'elepay-ruby-sdk/models/source_dto'
require 'elepay-ruby-sdk/models/source_req'
require 'elepay-ruby-sdk/models/source_response'
require 'elepay-ruby-sdk/models/source_status_type'

# APIs
require 'elepay-ruby-sdk/api/charge_api'
require 'elepay-ruby-sdk/api/customer_api'
require 'elepay-ruby-sdk/api/refund_api'

module ElepayApi
  class << self
    # Customize default settings for the SDK using block.
    #   ElepayApi.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
