=begin
#elepay API リファレンス

#elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。

The version of the OpenAPI document: 1.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'date'

module ElepayApi
  # 支払いオブジェクト
  class ChargeDto
    # Charge ID
    attr_accessor :id

    # 対象種類の表記
    attr_accessor :object

    # 本番モードかどうか - false テストモード - true 本番モード 
    attr_accessor :live_mode

    # 支払い金額
    attr_accessor :amount

    # 通貨コード (ISO_4217)
    attr_accessor :currency

    attr_accessor :payment_method

    attr_accessor :resource

    # お客様システム側のオーダーNo、例えば注文番号、決済IDなど
    attr_accessor :order_no

    # 支払い説明文
    attr_accessor :description

    # 支払いエキストラデータ
    attr_accessor :extra

    # 支払いメタデータ
    attr_accessor :metadata

    # Client IP アドレス
    attr_accessor :client_ip

    # 支払い済みフラグ
    attr_accessor :paid

    # 返金済みフラグ
    attr_accessor :refunded

    attr_accessor :refunds

    attr_accessor :status

    # Client SDK の認証情報
    attr_accessor :credential

    # 支払い時間のUTCタイムスタンプ
    attr_accessor :paid_time

    # 返金時間のUTCタイムスタンプ
    attr_accessor :refund_time

    # 支払い請求有効時間のUTCタイムスタンプ
    attr_accessor :expiry_time

    # 支払い締め時間のUTCタイムスタンプ
    attr_accessor :settle_time

    # 支払い新規時間のUTCタイムスタンプ
    attr_accessor :create_time

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'object' => :'object',
        :'live_mode' => :'liveMode',
        :'amount' => :'amount',
        :'currency' => :'currency',
        :'payment_method' => :'paymentMethod',
        :'resource' => :'resource',
        :'order_no' => :'orderNo',
        :'description' => :'description',
        :'extra' => :'extra',
        :'metadata' => :'metadata',
        :'client_ip' => :'clientIp',
        :'paid' => :'paid',
        :'refunded' => :'refunded',
        :'refunds' => :'refunds',
        :'status' => :'status',
        :'credential' => :'credential',
        :'paid_time' => :'paidTime',
        :'refund_time' => :'refundTime',
        :'expiry_time' => :'expiryTime',
        :'settle_time' => :'settleTime',
        :'create_time' => :'createTime'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'object' => :'String',
        :'live_mode' => :'Boolean',
        :'amount' => :'Integer',
        :'currency' => :'String',
        :'payment_method' => :'PaymentMethodType',
        :'resource' => :'ResourceType',
        :'order_no' => :'String',
        :'description' => :'String',
        :'extra' => :'Hash<String, String>',
        :'metadata' => :'Hash<String, String>',
        :'client_ip' => :'String',
        :'paid' => :'Boolean',
        :'refunded' => :'Boolean',
        :'refunds' => :'RefundsDto',
        :'status' => :'ChargeStatusType',
        :'credential' => :'String',
        :'paid_time' => :'Integer',
        :'refund_time' => :'Integer',
        :'expiry_time' => :'Integer',
        :'settle_time' => :'Integer',
        :'create_time' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ElepayApi::ChargeDto` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ElepayApi::ChargeDto`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'object')
        self.object = attributes[:'object']
      else
        self.object = 'charge'
      end

      if attributes.key?(:'live_mode')
        self.live_mode = attributes[:'live_mode']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = 'JPY'
      end

      if attributes.key?(:'payment_method')
        self.payment_method = attributes[:'payment_method']
      end

      if attributes.key?(:'resource')
        self.resource = attributes[:'resource']
      end

      if attributes.key?(:'order_no')
        self.order_no = attributes[:'order_no']
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'extra')
        if (value = attributes[:'extra']).is_a?(Hash)
          self.extra = value
        end
      end

      if attributes.key?(:'metadata')
        if (value = attributes[:'metadata']).is_a?(Hash)
          self.metadata = value
        end
      end

      if attributes.key?(:'client_ip')
        self.client_ip = attributes[:'client_ip']
      end

      if attributes.key?(:'paid')
        self.paid = attributes[:'paid']
      end

      if attributes.key?(:'refunded')
        self.refunded = attributes[:'refunded']
      end

      if attributes.key?(:'refunds')
        self.refunds = attributes[:'refunds']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'credential')
        self.credential = attributes[:'credential']
      end

      if attributes.key?(:'paid_time')
        self.paid_time = attributes[:'paid_time']
      end

      if attributes.key?(:'refund_time')
        self.refund_time = attributes[:'refund_time']
      end

      if attributes.key?(:'expiry_time')
        self.expiry_time = attributes[:'expiry_time']
      end

      if attributes.key?(:'settle_time')
        self.settle_time = attributes[:'settle_time']
      end

      if attributes.key?(:'create_time')
        self.create_time = attributes[:'create_time']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          object == o.object &&
          live_mode == o.live_mode &&
          amount == o.amount &&
          currency == o.currency &&
          payment_method == o.payment_method &&
          resource == o.resource &&
          order_no == o.order_no &&
          description == o.description &&
          extra == o.extra &&
          metadata == o.metadata &&
          client_ip == o.client_ip &&
          paid == o.paid &&
          refunded == o.refunded &&
          refunds == o.refunds &&
          status == o.status &&
          credential == o.credential &&
          paid_time == o.paid_time &&
          refund_time == o.refund_time &&
          expiry_time == o.expiry_time &&
          settle_time == o.settle_time &&
          create_time == o.create_time
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, object, live_mode, amount, currency, payment_method, resource, order_no, description, extra, metadata, client_ip, paid, refunded, refunds, status, credential, paid_time, refund_time, expiry_time, settle_time, create_time].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        ElepayApi.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end
        
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end
  end
end
