=begin
#elepay API リファレンス

#elepay APIはRESTをベースに構成された決済APIです。支払い処理、返金処理など、決済に関わる運用における様々なことができます。

The version of the OpenAPI document: 1.1.1

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.2.2

=end

require 'date'

module ElepayApi
  class PaymentMethodType
    ALIPAY = "alipay".freeze
    APPLEPAY = "applepay".freeze
    APPLEPAY_CN = "applepay_cn".freeze
    CREDITCARD = "creditcard".freeze
    GOOGLEPAY = "googlepay".freeze
    PAYPAL = "paypal".freeze
    UNIONPAY = "unionpay".freeze
    LINEPAY = "linepay".freeze
    PAIDY = "paidy".freeze
    PAYPAY = "paypay".freeze
    DOCOMOPAY = "docomopay".freeze
    ATONE = "atone".freeze
    ORIGAMIPAY = "origamipay".freeze
    MERPAY = "merpay".freeze
    WECHATPAY = "wechatpay".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = PaymentMethodType.constants.select { |c| PaymentMethodType::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #PaymentMethodType" if constantValues.empty?
      value
    end
  end
end
